In [1]:
import numpy

In [2]:
vector = [1, 2, 3]

In [3]:
print(type(vector))

<class 'list'>


In [4]:
nvector = numpy.array(vector)

In [5]:
nvector.shape

(3,)

In [6]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [7]:
nmatrix = numpy.array(matrix)

In [8]:
nmatrix.shape

(3, 3)

In [9]:
x = [
    [[1, 2, 3], [5, 2, 3], [1, 2, 8]],
    [[1, 5, 3], [1, 2, 3], [1, 2, 5]],
   [[1, 2, 7], [6, 5, 3], [1, 5, 3]]
]

In [10]:
x1 = numpy.array(x)


In [11]:
x1.shape

(3, 3, 3)

In [12]:
narr = numpy.array([1, 2, 3])
narr

array([1, 2, 3])

In [13]:
numpy.resize(narr, (6, 5))

array([[1, 2, 3, 1, 2],
       [3, 1, 2, 3, 1],
       [2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2],
       [3, 1, 2, 3, 1],
       [2, 3, 1, 2, 3]])

In [14]:
narr.resize((3, 3), refcheck = False)
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
matrix = numpy.ones((4, 5))
matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
matrix = numpy.zeros((4, 6))

In [18]:
matrix

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
numpy.diag(narr)

array([1, 0, 0])

In [20]:
numpy.repeat((4, 3, 2), 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [21]:
m1 = numpy.ones((4, 5), int)
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
m2 = numpy.zeros((4, 5), int)
m2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
numpy.vstack([m1, m2])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
numpy.hstack([m1, m2])

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

In [25]:
x = numpy.array([1, 2, 3])
y = numpy.array([3, 6, 8])

In [26]:
z = x * y
z

array([ 3, 12, 24])

In [27]:
x ** 10

array([    1,  1024, 59049])

In [28]:
x.dot(y)

39

In [29]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [31]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [32]:
narr.sum()

6

In [33]:
narr.max()

3

In [34]:
narr.min()

0

In [35]:
narr.argmax()

2

In [36]:
narr.argmin()

3

In [37]:
narr.mean()

0.6666666666666666

In [38]:
narr.std()

1.0540925533894598

In [39]:
mr = numpy.arange(15) ** 2

In [40]:
mr


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [41]:
mr[5]


25

In [42]:
mr[:5]

array([ 0,  1,  4,  9, 16])

In [43]:
mr[-2]

169

In [44]:
mr[-2:]

array([169, 196])

In [45]:
mr[2:]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196])

In [46]:
mr[2:-2]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [47]:
mr[1:6:2]

array([ 1,  9, 25])

In [48]:
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [49]:
mr[10::-2]

array([100,  64,  36,  16,   4,   0])

In [50]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [51]:
narr[0:3]

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
narr[0:2, 1:3]

array([[2, 3],
       [0, 0]])

In [53]:
narr[::2, -1]

array([3, 0])

In [54]:
narr[narr >= 2]

array([2, 3])

In [55]:
narr >= 2

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [56]:
marr = narr[-1]
marr

array([0, 0, 0])

In [57]:
marr[:] = 1
marr

array([1, 1, 1])

In [58]:
marr[:2] = 2
marr

array([2, 2, 1])

In [59]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [60]:
marr = narr.copy()
marr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [61]:
marr[:] = 0
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [62]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [63]:
tarr = numpy.random.randint(0, 10, (3,4))
tarr

array([[3, 1, 2, 6],
       [9, 5, 3, 3],
       [7, 7, 1, 1]])

In [64]:
for r in tarr:
    r = r ** 2
    print(r)

[ 9  1  4 36]
[81 25  9  9]
[49 49  1  1]


In [65]:
for i, r in enumerate(tarr):
    print('index(' + str(i) + ') is:' , r)

index(0) is: [3 1 2 6]
index(1) is: [9 5 3 3]
index(2) is: [7 7 1 1]


In [66]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [67]:
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [68]:
list(zip(narr, marr))

[(array([1, 2, 3]), array([0, 0, 0])),
 (array([0, 0, 0]), array([0, 0, 0])),
 (array([2, 2, 1]), array([0, 0, 0]))]

In [69]:
arr = [3 , 4 , 22, 9, 14, 6 , 7]

In [70]:
arr = numpy.array(arr)
arr

array([ 3,  4, 22,  9, 14,  6,  7])

In [71]:
len(arr) // 2

3

In [72]:
p = arr[len(arr) // 2]
p

9

In [73]:
l = [x for x in arr if x < p]
l

[3, 4, 6, 7]

In [74]:
r = [x for x in arr if x > p]
r

[22, 14]

In [75]:
m = [x for x in arr if x == p]
m

[9]

In [76]:
l + m + r

[3, 4, 6, 7, 9, 22, 14]

In [77]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    arr = numpy.array(arr)
    p = arr[len(arr) // 2]
    l = [x for x in arr if x < p]
    m = [x for x in arr if x == p]
    r = [x for x in arr if x > p]
    return quicksort(l) + m + quicksort(r)

In [78]:
h = [5, 1000, 50, 45, 65, 0, 2, 3, 87, 90, -1, 20, 14]

In [88]:
quicksort(h)

[-1, 0, 2, 3, 5, 14, 20, 45, 50, 65, 87, 90, 1000]